#pragma config(Motor,  port1,           Cannon,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Elevator,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Read Me:
	This code is just to test interaction between controller and robot
	NOT competition use just for driver controls
	Also fine to help the driver just practice without auton
*/
task main()
{
	//GAY is OKAY
	while(true)
	{
		int leftside=vexRT[Ch3];		//sets respective buttons or joysticks to a variable for easier to read code
	  int rightside=vexRT[Ch2];
	  int clawup=vexRT[Btn6U];
	  int clawdown=vexRT[Btn6D];
	 

	  //creates "deadspace" to prevent motor burnout when joystick not pressed
	  //can be changed to lower numbers like 5 to give driver more control but don't go much lower

	  //Left controls
		if (leftside >= 10)
		{
			motor[LeftF]=leftside;
			motor[LeftB]=leftside;			//sets front and back motors on left to joystick input 10 to 127
		}
		else if (leftside <= -10)			//-127 to -10
		{
			motor[LeftF]=leftside;
			motor[LeftB]=leftside;
		}
		else			//if between -10 and 10 set motors to 0
		{
			motor[LeftF]=0;
			motor[LeftB]=0;
		}

		//Right controls
		if (rightside >= 10)		//same comments apply from above
		{
			motor[RightF]=rightside;
			motor[RightB]=rightside;
		}
		else if (rightside <= -10)
		{
			motor[RightF]=rightside;
			motor[RightB]=rightside;
		}
		else
		{
			motor[RightF]=0;
			motor[RightB]=0;
		}

		//claw stuff
		if (clawup == 1)						//used for claw (probably the cap claw unless changed)
		{														//used to raise and lower the claw when respective buttons pressed down
			motor[Claw]=127;
		}
		else if (clawdown == 1)
		{
			motor[Claw]=-127;
		}
		else												//if both buttons pressed claw will go up due to order of if statements
		{
			motor[Claw]=0;				//due to gravity claw will go down but slowly (test different positive values to try to counteract gravity)
		}
		//I'll add the other stuff later
	}
}
