#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          clawMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//GAY is OKAY
	while(true)
	{
		int leftside=vexRT[Ch3];
	  int rightside=vexRT[Ch2];
	  int clawup=vexRT[Btn6U];
	  int clawdown=vexRT[Btn6D];
	  
	  //Left controls
		if (leftside >= 10)
		{
			motor[LeftF]=leftside;
			motor[LeftB]=leftside;
		}
		else if (leftside <= -10)
		{
			motor[LeftF]=leftside;
			motor[LeftB]=leftside;
		}
		else 
		{
			motor[LeftF]=0;
			motor[LeftB]=0;
		}
		
		//Right controls
		if (rightside >= 10)
		{
			motor[RightF]=rightside;
			motor[RightB]=rightside;
		}
		else if (rightside <= -10)
		{
			motor[RightF]=rightside;
			motor[RightB]=rightside;
		}
		else 
		{
			motor[RightF]=0;
			motor[RightB]=0;
		}
	
		//claw stuff
		if (clawup == 1) 
		{
			motor[clawMotor]=127;
		}
		else if (clawdown == 1) 
		{
			motor[clawMotor]=-127;	
		}
		else
		{
			motor[clawMotor]=0;	
		}
	}
}
