#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Elevator,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Cannon,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Cannon2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

/*
Read Me:
This is jsut to find the best encoder value for a 360 degree spin which
can be converted easily to any other degree.
Always use the encoder for the while loop that is going to be positive.
turning right use left encoder. Turning left use right encoder
*/
task main()
{
resetMotorEncoder(LeftF);
int encVal = 1000;
while(getMotorEncoder(LeftF) < encVal){		//turn right for 360
	motor[LeftF]=motor[LeftB]=127;				//lower speed for precision
	motor[RightF]=motor[RightB]=-127;			//higher for faster use during autonomous
}


}
