#pragma config(Motor,  port1,           LeftF,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftB,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
task main()
{
//This is a test
wait1Msec(750); 		//Robot do nothing
motor[LeftF]=motor[LeftB]=63;
motor[RightF]=motor[RightB]=63;
wait1Msec(500);			//Robot go forward
motor[LeftF]=motor[LeftB]=63;
motor[RightF]=motor[RightB]=-63;
wait1Msec(1000);		//Robot turn left (point)
motor[LeftF]=motor[LeftB]=-63;
motor[RightF]=motor[RightB]=63;
wait1Msec(1000);		//Robot turn right (point)
motor[LeftF]=motor[LeftB]=-63;
motor[RightF]=motor[RightB]=-63;
wait1Msec(750);			//Robot go backwards
motor[LeftF]=motor[LeftB]=0;
motor[RightF]=motor[RightB]=0;
wait1Msec(250);			//Robot stop

}
*/
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
        // All activities that occur before the competition starts
        // Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Use command for no auton   AuonomousCodePlaceholderForTesting();
  // .....................................................................................

//This is a test
wait1Msec(750); 		//Robot do nothing
motor[LeftF]=63;
motor[LeftB]=63;
motor[RightF]=63;
motor[RightB]=63;
wait1Msec(500);			//Robot go forward
motor[LeftF]=63;
motor[LeftB]=63;
motor[RightF]=-63;
motor[RightB]=-63;
wait1Msec(1000);		//Robot turn left (point)
motor[LeftF]=-63;
motor[LeftB]=-63;
motor[RightF]=63;
motor[RightB]=63;
wait1Msec(1000);		//Robot turn right (point)
motor[LeftF]=-63;
motor[LeftB]=-63;
motor[RightF]=-63;
motor[RightB]=-63;
wait1Msec(750);			//Robot go backwards
motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);			//Robot stop
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
        // User control code here, inside the loop

        while (true)
        {
          // This is the main execution loop for the user control program. Each time through the loop
          // your program should update motor + servo values based on feedback from the joysticks.

          // .....................................................................................
          // Insert user code here. This is where you use the joystick values to update your motors, etc.
          // Use UserControlCodePlaceholderForTesting(); for no control
          // .....................................................................................



  	int leftside=vexRT[Ch3];
  	int rightside=vexRT[Ch2];
  	//Left controls
  	if (leftside >= 10){
  		motor[LeftF]=motor[LeftB];
  	}
  	else if (leftside <= -10){
  		motor[LeftF]=motor[LeftB];
  	}
  	else {
  		motor[LeftF]=motor[LeftB]=0;
  	}
  	//Right controls
  	if (rightside >= 10){
  		motor[RightF]=motor[RightB];
  	}
  	else if (rightside <= -10){
  		motor[RightF]=motor[RightB];
  	}
  	else {
  		motor[RightF]=motor[RightB]=0;
  	}

        }
}
