#pragma config(Motor,  port1,           Arm,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Read Me:
	Literally only used for autonomous testing
	Make sure to copy all changes from BotCoin.c's autonomous into here
	also CHANGE if we can get some enconders because wait statements are inconsistent
*/
task main()
{
//change direction in accordance with notebook (1-6)
resetMotorEncoder(LeftF);
resetMotorEncoder(LeftB);
resetMotorEncoder(RightF);
resetMotorEncoder(RightB);
int direction = 7;
int encVal = 1000;
//Use encoder Values from other file
//REMOVE THIS WAIT STATE FOR COMPETITION IT IS ONLY TO GET HANDS OUT OF THE WAY
wait1Msec(1000);


if(direction==1){
	//this will be on the far side from flags
	//it will pick flat cap put on closest low scoring spot and park
}
else if(direction==2){
	
}
else if(direction==3){		//this just flips the cap on the near side of the flag and parks
													//these two are only used if alliance scores better than us on respective side
													//as such will probably not be used as most robots will score flags
	//go to cap											
	while(getMotorEncoder(LeftF) < 1500){
		motor[LeftF]=motor[LeftB]=127;
		motor[RightF]=motor[RightB]=127;
	}
	//lower arm
	motor[Arm]=-63;
	wait1Msec(500);
	//move under cap
	resetMotorEncoder(RightF);			//**
	while(getMotorEncoder(RightF) < 500){
		motor[LeftF]=motor[LeftB]=63;
		motor[RightF]=motor[RightB]=63;
	}
	//raise arm to flip cap
	motor[Arm]=127;
	wait1Msec(750);
	
}
//*
else if(direction==4){
	//go to cap											//**
	while(getMotorEncoder(LeftF) < 1500){
		motor[LeftF]=motor[LeftB]=127;
		motor[RightF]=motor[RightB]=127;
	}
	//lower arm
	motor[Arm]=-63;
	wait1Msec(500);
	//move under cap
	resetMotorEncoder(RightF);			//***
	while(getMotorEncoder(RightF) < 500){
		motor[LeftF]=motor[LeftB]=63;
		motor[RightF]=motor[RightB]=63;
	}
	//raise arm to flip cap
	motor[Arm]=127;
	wait1Msec(750);
	
}
else{		//to account for user error in inputing the variable
	motor[LeftF]=motor[LeftB]=-127;
	motor[RightF]=motor[RightB]=127;
	wait1Msec(5000);
}
