#pragma config(Motor,  port1,           Cannon,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Elevator,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Read Me:
	This code is only used to test motors and if they work in both directions never inteneded for
  competition use.
  Important info about how motors works is below
  Also don't put ANY code before pragmas including comments. RobotC doesn't like that
*/

task main()
{
//MC29 vs. HBridge?
//yes, MC29 need 3 prongs and HBridge can directly connect 2 prongs
//Also HBridge update faster than MC29 by like a few ms(milliseconds)
//This is a motor test
wait1Msec(750); 		//Robot do nothing

motor[LeftF]=63;
motor[LeftB]=63;
motor[RightF]=63;
motor[RightB]=63;
wait1Msec(1000);			//Robot go forward

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);				//robot stop

motor[LeftF]=63;
motor[LeftB]=63;
motor[RightF]=-63;
motor[RightB]=-63;
wait1Msec(1000);		//Robot turn left (point)

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);			//Robot stop

motor[LeftF]=-63;
motor[LeftB]=-63;
motor[RightF]=63;
motor[RightB]=63;
wait1Msec(1000);		//Robot turn right (point)

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);			//Robot stop

motor[LeftF]=-63;
motor[LeftB]=-63;
motor[RightF]=-63;
motor[RightB]=-63;
wait1Msec(1000);			//Robot go backwards

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);			//Robot stop

//can add later stuff for: claw,elevator,cannon,etc. below

}
