#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//MC29 vs. HBridge?
//yes, MC29 need 3 prongs and HBridge can directly connect 2 prongs
//Also HBridge update faster than MC29
//This is a motor test
wait1Msec(750); 		//Robot do nothing

motor[LeftF]=63;
motor[LeftB]=63;
motor[RightF]=63;
motor[RightB]=63;
wait1Msec(1000);			//Robot go forward

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);				//robot stop

motor[LeftF]=63;
motor[LeftB]=63;
motor[RightF]=-63;
motor[RightB]=-63;
wait1Msec(1000);		//Robot turn left (point)

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);			//Robot stop

motor[LeftF]=-63;
motor[LeftB]=-63;
motor[RightF]=63;
motor[RightB]=63;
wait1Msec(1000);		//Robot turn right (point)

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);			//Robot stop

motor[LeftF]=-63;
motor[LeftB]=-63;
motor[RightF]=-63;
motor[RightB]=-63;
wait1Msec(1000);			//Robot go backwards

motor[LeftF]=0;
motor[LeftB]=0;
motor[RightF]=0;
motor[RightB]=0;
wait1Msec(250);			//Robot stop

}
